//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : BillInfo.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

public class BillInfo
{
	private String billInfoId;
	private Float amount;
	private Float discountAmount;
	private Float payableAmount;
	private Float cash;
	private Integer points;
	private Float pointsToCash;
	public void createBillInfo(String billInfoId)
	{
	}
	
	public void setBillInfoId(String billInfoId)
	{
	}
	
	public void setAmount(Float amount)
	{
	}
	
	public void setDiscountAmount(Float discountAmount)
	{
	}
	
	public void setCash(Float cash)
	{
	}
	
	public void setPoints(Integer points)
	{
	}
	
	public Float returnBalance()
	{
	    return 0f;
	}
	
	public Float getAmount()
	{
	    return 0f;
	}
	
	public Float getDiscountAmount()
	{
	    return 0f;
	}
	
	public Float getPayableAmount()
	{
	    return 0f;
	}
	
	public Float getCash()
	{
	    return 0f;
	}
	
	public Integer getPoints()
	{
	    return 0;
	}
	
	public Float getPointsToCash()
	{
	    return 0f;
	}
}
