package sg.edu.nus.iss.se23pt2.pos;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Category.java
//  @ Date : 3/8/2015
//  @ Author : Nikhil Metrani
//
//



/** */
public class Category {
    /** */
    private String code = null;
    
    /** */
    private String name = null;
    
    /** */
    public ArrayList<Vendor> vendors;
    
    /** */
    public Product Unnamed4;
    
    /** */
    public Category() {
    	this(null, null);
    }

	/** */
    public Category(String code, String name) {
    	this.code = code;
    	this.name = name;
    	this.vendors = new ArrayList<Vendor>();
    }
    
    public void setCode(String code){
    	this.code = code;
    }
    
    /** */
    public String getCode() {
    	return this.code;
    }
    
    /** */
    public void setName(String name) {
    	this.name = name;
    }
    
    /** */
    public String getName() {
    	return this.name;
    }
    
    /** */
    public Vendor addVendor(Vendor vendor) {
    	//TO-DO
    	return vendor;
    }
    
    /** */
    public Vendor getVendor(String name) {
    	//TO DO
    	Vendor v = new Vendor();;
    	return v;
    }
    
    /** */
    public ArrayList<Vendor> getVendors() {
    	//TO-DO
    	return (ArrayList<Vendor>) this.vendors;
    }
    
    /** */
    public void removeVendor(String name) {
    	// TO DO
    }
}
