//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Discount.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Discount.java
//  @ Date : 15/03/2015
//  @ Author : Niu Yiming
//
//

public class Discount
{
	private String discountCode;
	private String description;
	private String startDate;
	private String periodInDays;
	private Integer discountPercentage;
	private String applicableTo;

    public Discount(String discountCode, String description, String startDate, String periodInDays, Integer discountPercentage, String applicableTo)
    {
    	discountCode = this.discountCode;
    	description = this.description;	
        
    }
    
	public String getDiscountCode()
	{
	    return null;
	}
	
	public String getDiscountDescription()
	{
	    return null;
	}
	
	public String getStartDate()
	{
	    return null;
	}
	
	public String getPeriodInDays()
	{
	    return null;
	}
	
	public Integer getDiscountPercentage()
	{
	    return 0;
	}
	
	public void setDiscountPercentage(int discountPercentage){
	    this.discountPercentage = discountPercentage;
	}
	
	public String getApplicableTo()
	{
	    return null;
	}
	
	public Boolean isDiscountForMember()
	{
	    return null;
	}
	
	public Boolean isWithInDateRange()
	{
	    return false;
	}
	
	public Boolean isMemberFirst()
	{
	    return false;
	}
}
