//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Discount.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Discount.java
//  @ Date : 15/03/2015
//  @ Author : Niu Yiming
//
//

public class Discount
{
	private String discountCode;
	private String description;
	private String startDate;
	private String periodInDays;
	private Integer discPct;
	private String applicableTo;

    public Discount(String discountCode, String description, String startDate, String periodInDays, Integer discPct, String applicableTo)
    {
    	this.discountCode = discountCode;
    	this.description = description;	
    	this.startDate = startDate;
    	this.periodInDays = periodInDays;
    	this.discPct = discPct;
    	this.applicableTo = applicableTo;
    }
    
	public String getDiscountCode()
	{
	    return discountCode;
	}
	
	public String getDiscountDescription()
	{
	    return description;
	}
	
	public String getStartDate()
	{
	    return startDate;
	}
	
	public String getPeriodInDays()
	{
	    return periodInDays;
	}
	
	public Integer getDiscPct()
	{
	    return discPct;
	}
	
	public void setDiscPct(int discPct){
	    this.discPct = discPct;
	}
	
	public String getApplicableTo()
	{
	    return applicableTo;
	}
	
	public Boolean isWithInDateRange()
	{
	    return false;
	}
	
	public Boolean isDiscountForMember()
	{
	    return null;
	}
	
	public Boolean isMemberFirst()
	{
	    return false;
	}
}
