package sg.edu.nus.iss.se23pt2.pos;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Inventory.java
//  @ Date : 3/8/2015
//  @ Author : Nikhil Metrani
//
//



/** */
public class Inventory {
    /** */
    public ArrayList<Product> products;
    
    public Inventory (ArrayList<Product> products) {
    	this.products = products;
    }
    
    /** */
    public ArrayList<Product> getAllProducts() {
    	//TO-DO
    	ArrayList<Product> pr = new ArrayList<Product>();
    	return pr;
    }
    
    /** */
    public Product getProduct(String prodId) {
    	//TO-DO
    	Product pr = new Product();
    	return pr;
    }
    
    /** */
    public ArrayList<Product> getProducts(String catId) {
    	//TO-DO
    	ArrayList<Product> pr = new ArrayList<Product>();
    	return pr;
    }
    
    /** */
    public ArrayList<Product> getProductsBelowThresholdQuantity() {
    	//TO-DO
    	ArrayList<Product> pr = new ArrayList<Product>();
    	return pr;
    }
    
    /** */
    public ArrayList<Product> getProductsBelowThresholdQuantity(String catId) {
    	//TO-DO
    	ArrayList<Product> pr = new ArrayList<Product>();
    	return pr;
    }
    
    /** */
    public Product addProduct(String catId, String name) {
    	//TO-DO
    	Product pr = new Product();
    	return pr;
    }
    
    /** */
    public Product removeProduct(String prodId, Integer quantity) {
    	//TO-DO
    	Product pr = new Product();
    	return pr;
    }
    
    /** */
    public PurchaseOrder generatePurchaseOrder() {
    	//TO-DO
    	PurchaseOrder pr = new PurchaseOrder();
    	return pr;
    }
    
    /** */
    public PurchaseOrder generatePurchaseOrder(String catId) {
    	//TO-DO
    	PurchaseOrder pr = new PurchaseOrder();
    	return pr;
    }
}
