package sg.edu.nus.iss.se23pt2.pos;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Item.java
//  @ Date : 3/8/2015
//  @ Author : Nikhil Metrani
//
//



/** */
public class Item {
    /** */
    private String productId;
    
    /** */
    private Integer quantity;
    
    /** */
    private Float price;
    
    public Item() {
    	this(null, 0, Float.valueOf(0));
    }
    
    public Item(String productId, Integer quantity, Float price) {
    	this.productId = productId;
    	this.quantity = quantity;
    	this.price = price;
    }
    
    public void setProductId(String id) {
    	this.productId = id;
    }
    
    public String getProductId() {
    	return this.productId;
    }
    
    public void setQuantity(Integer quantity) {
    	this.quantity = quantity;
    }
    
    public Integer getQuantity() {
    	return this.quantity;
    }
    
    public void setPrice(Float price) {
    	this.price = price;
    }
    
    public Float getPrice() {
    	return this.price;
    }
}
