//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Member.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

public class Member
{
	private String memberId;
	private String memberName;
	private Integer loyaltyPoints = -1;
	public void createMember(String memberId, String memberName)
	{
	}
	
	public String getMemberId()
	{
	    return null;
	}
	
	public String getMemberName()
	{
	    return null;
	}
	
	public Integer getLoyaltyPoints()
	{
	    return 0;
	}
	
	public void addLoyaltyPoints(Integer points)
	{
	}
	
	public void deductLoyaltyPoints(Integer points)
	{
	}
	
	public Boolean isNewMember()
	{
	    return false;
	}
}
