package sg.edu.nus.iss.se23pt2.pos;

/**
 * Generated by StarUML(tm) Java Add-In
 * 
 * @Project : SouvenirStore
 * @Date : 15/03/2015
 * @Author : Niu Yiming
 */

public class Member extends Customer {
    
    private String name;
    private String id;
    private int loyaltyPoints = 0;
    
    public Member(String name, String id) {
    	this.name = name;
    	this.id = id;
    }
    
    public String getId() {
    	return id;
    }
    
    public String getName() {
    	return name;
    }
    
    public void setName(String name) {
    	this.name = name;
    }
    
    public int getLoyaltyPoints() {
    	return loyaltyPoints;
    }
    
    public void addLoyaltyPoints(int points) {
    	this.loyaltyPoints += points;
    }
    
    // Deduct LoyaltyPoints only when the member has enough points.
    public void deductLoyaltyPoints(int points) {
    	int tempPts = this.loyaltyPoints - points;
    	if(tempPts >= 0) this.loyaltyPoints = tempPts;
    }
 
}
