package sg.edu.nus.iss.se23pt2.pos;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Member.java
//  @ Date : 3/8/2015
//  @ Author : Nikhil Metrani
//
//



/** */
public class Member extends Customer {
    
	/** */
    private String firstName;
    
    /** */
    private String lastName;
    
    /** */
    private Integer loyaltyPoints;
    
    public Member() {
    	this(null, null, null, -1);
    }
    
    /** */
    public Member(String id, String firstName, String lastName) {
    	this(id, firstName, lastName, -1);
    }
    
    /** */
    public Member(String id, String firstName, String lastName, Integer loyaltyPoints) {
    	super.setId(id);
    	this.firstName = firstName;
    	this.lastName = lastName;
    	this.loyaltyPoints = loyaltyPoints;
    }
    
    /** */
    public void setFirstName(String name) {
    	this.firstName = name;
    }
    
    /** */
    public String getFirstName() {
    	return this.firstName;
    }
    
    /** */
    public void setLastName(String name) {
    	this.lastName = name;
    }
    
    /** */
    public String getLastName() {
    	return this.lastName;
    }
    
    /** */
    public String getFullName() {
    	return this.firstName + " " + this.lastName;
    }
    
    /** */
    public Integer getLoyaltyPoints() {
    	return this.loyaltyPoints;
    }
    
    /** */
    public void addLoyaltyPoints(Integer points) {
    	//To-Do
    }
    
    /** */
    public void deductLoyaltyPoints(Integer points) {
    	//TO-DO
    }
    
    /** */
    public Boolean isNewMember() {
    	//TO-DO
    	return true;
    }
}
