//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : PrinterFactory.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

public class PrinterFactory
{
	private static Object printerFactory;
	private void createPrinterFactory()
	{
	}
	
	public static PrinterFactory getInstance()
	{
	    return new PrinterFactory();
	}
	
	public Printer getProductLabelPrinter()
	{
	    return null;
	}
	
	public Printer getReceiptPrinter()
	{
	    return null;
	}
	
	public Printer getReportPrinter()
	{
	    return null;
	}
}
