//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Product.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

public class Product
{
	private String productId;
	private String productName;
	private String description;
	private Integer availableQty;
	private Float price;
	private String barcodeNum;
	private Integer reorderThresholdQty;
	private Integer orderQty;
	public void createProduct(String productId, String productName, Integer availableQty, Float price)
	{
	}
	
	public void setDescription(String description)
	{
	}
	
	public void setPrice(Float price)
	{
	}
	
	public void setReorderThresholdQty(Integer reorderThresholdQty)
	{
	}
	
	public void setOrderQty(Integer orderQty)
	{
	}
	
	public String getProductId()
	{
	    return null;
	}
	
	public String getProductName()
	{
	    return null;
	}
	
	public String getDescription()
	{
	    return null;
	}
	
	public Integer getAvailableQty()
	{
	    return 0;
	}
	
	public Float getPrice()
	{
	    return 0f;
	}
	
	public String getBarcodeNum()
	{
	    return null;
	}
	
	public Integer getReorderThresholdQty()
	{
	    return 0;
	}
	
	public Integer getOrderQty()
	{
	    return 0;
	}
	
	public void addQty(Integer qty)
	{
	}
	
	public void deductQty(Integer qty)
	{
	}
}
