package sg.edu.nus.iss.se23pt2.pos;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Product.java
//  @ Date : 3/8/2015
//  @ Author : Nikhil Metrani
//
//



/** */
public class Product {
    /** */
    private String id;
    
    /** */
    private String name;
    
    /** */
    private String description;
    
    /** */
    private Integer availableQuantity;
    
    /** */
    private Float price;
    
    /** */
    private String barcodeNumber;
    
    /** */
    private Integer reorderThresholdQuantity;
    
    /** */
    private Integer orderQuantity;
	
    /** */
    public Category category;
    
	/** */
    public Product() {
		this(null, null);
    }
	
    /** */
    public Product(String id, String name) {
    	this.id = id;
    	this.name = name;
    	this.description = null;
    	this.availableQuantity = 0;
    	this.reorderThresholdQuantity = 0;
    	this.price = Float.valueOf(0);
    	this.barcodeNumber = "BARCODE101";
    	this.orderQuantity = 0;
    	this.category = null;
    }
    
    public void setId(String id) {
    	this.id = id;
    }
    
    public String getId() {
    	return this.id;
    }
    
    /** */
    public void setName(String name) {
    	this.name = name;
    }
    
    /** */
    public String getName() {
    	return this.name;
    }

    /** */
    public void setDescription(String description) {
    	this.description = description;
    }
    
    /** */
    public String getDescription() {
    	return this.description;
    }

    /** */
    public void setPrice(Float price) {
    	this.price = Float.valueOf(price);
    }
    
    /** */
    public Float getPrice() {
    	return this.price;
    }

    /** */
    public void setReorderThresholdQty(Integer reorderThresholdQty) {
    	this.reorderThresholdQuantity = reorderThresholdQty;
    }
    
    /** */
    public Integer getReorderThresholdQuantity() {
    	return this.reorderThresholdQuantity;
    }

    /** */
    public void setOrderQuantity(Integer orderQty) {
    	this.orderQuantity = orderQty;
    }
 
    /** */
    public Integer getOrderQuantity() {
    	return this.orderQuantity;
    }
    
    /** */
    public Integer getAvailableQuantity() {
    	return this.availableQuantity;
    }

    public void setAvailableQuantity (Integer availableQuantity) {
        this.availableQuantity = availableQuantity;
    }

    public void setBarcodeNumber(String barcode) {
    	this.barcodeNumber = barcode;
    }
    /** */
    public String getBarcodeNumber() {
    	return this.barcodeNumber;
    }
    
    /** */
    public void addQuantity(Integer qty) {
    	//TO-DO
    }
    
    /** */
    public void deductQuantity(Integer qty) {
    	//To-DO
    }
}
