//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Sequence.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

public class Sequence
{
	private String sequenceType;
	private String prefix="";
	private Integer nextNumber = 1;
	private Integer incrementBy = 1;

	public Sequence(String sequenceType)
	{
	    this.sequenceType = sequenceType;
	}
	
	public void setPrefix(String prefix)
	{
	    this.prefix = prefix;
	}
	
	public void setNextNumber(Integer nextNumber)
	{
	    this.nextNumber = nextNumber;
	}
	
	public void setIncrementBy(Integer incrementBy)
	{
	    this.incrementBy = incrementBy;
	}
	
	public String getSequenceType()
	{
	    return this.sequenceType;
	}
	
	public String getPrefix()
	{
	    return this.prefix;
	}
	
	public Integer getNextNumber()
	{
	    return this.nextNumber;
	}
	
	public Integer getIncrementBy()
	{
	    return this.incrementBy;
	}
	
	public String getNextSequence(){
	    String retVal = prefix + this.nextNumber;
	    this.nextNumber = this.nextNumber + this.incrementBy;
	    return retVal;
	}
	
	@Override
	public String toString(){
	    return this.sequenceType + "," + this.prefix + "," + this.nextNumber + "," + this.incrementBy;
	}
	
	@Override
	public boolean equals(Object obj){
        if(obj instanceof Sequence){
            return this.sequenceType.equals(((Sequence)obj).sequenceType);
        }
        return false;
	}
}
