//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : SequenceGenerator.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

import java.util.HashMap;
import java.util.Map;

import sg.edu.nus.iss.se23pt2.pos.datastore.DataStoreFactory;

public class SequenceGenerator
{
	private static final SequenceGenerator sequenceGenerator = new SequenceGenerator();
	private Map<String, Sequence> sequences = new HashMap<String, Sequence>();
	private SequenceGenerator()
	{
	}
	
	public static SequenceGenerator getInstance()
	{
	    return sequenceGenerator;
	}
	
	public synchronized String getNextSequence(String sequenceType)
	{
	    String retVal = "";
	    if(sequences.containsKey(sequenceType)){
	        retVal = sequences.get(sequenceType).getNextSequence();
	        try {
                DataStoreFactory.getInstance().getSequenceGeneratorDS().update(sequences.get(sequenceType));
            } catch (Exception e) {
                e.printStackTrace();
            }
	    }
	    return retVal;
	}
	
	public void addSequence(Sequence sequence)
	{
	    sequences.put(sequence.getSequenceType(), sequence);
	}
}
