//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : SequenceGenerator.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

import java.util.HashMap;
import java.util.Map;

import sg.edu.nus.iss.se23pt2.pos.datastore.DataStoreFactory;

public class SequenceGenerator
{
	private static final SequenceGenerator sequenceGenerator = new SequenceGenerator();
	private Map<String, Sequence> sequences = new HashMap<String, Sequence>();

	public static final String TRANSACTION_SEQ = "TRANSACTION";

	private SequenceGenerator()
	{
	}
	
	public static SequenceGenerator getInstance()
	{
	    return sequenceGenerator;
	}
	
	public synchronized String getNextSequence(String sequenceType)
	{
	    String retVal = "";
	    if(sequences.containsKey(sequenceType)){
	        retVal = sequences.get(sequenceType).getNextSequence();
	        try {
                DataStoreFactory.getInstance().getSequenceDS().update(sequences.get(sequenceType));
            } catch (Exception e) {
                e.printStackTrace();
            }
	    }
	    /**
	     * Nikhil Metrani
	     * If the sequence generator does not exist, lets create one
	     * It's easier to handle it here once than doing it everywhere else
	     * */
	    else {
	    	Sequence s = new Sequence(sequenceType);
	    	/**
	    	 * Nikhil Metrani
	    	 * Do we need to set the prefix here?
	    	 * Transaction prefix does not contain a trailing forward slash as opposed to Product.
	    	 * Let's handle this within the Product*/
	    	//s.setPrefix(sequenceType);
	    	this.addSequence(s);
	    	retVal = this.getNextSequence(sequenceType);
	    }
	    return retVal;
	}
	
	public void addSequence(Sequence sequence)
	{
	    sequences.put(sequence.getSequenceType(), sequence);
	}
}
