//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Sequence.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

public class Sequence
{
	private String sequenceType;
	private String prefix;
	private Integer nextNumber = 1;
	private Integer incrementBy = 1;
	public void createSequence(String sequenceType)
	{
	}
	
	public void setPrefix(String prefix)
	{
	}
	
	public void setNextNumber(Integer nextNumber)
	{
	}
	
	public void setIncrementBy(Integer incrementBy)
	{
	}
	
	public String getSequenceType()
	{
	    return null;
	}
	
	public String getPrefix()
	{
	    return null;
	}
	
	public Integer getNextNumber()
	{
	    return 0;
	}
	
	public Integer getIncrementBy()
	{
	    return 0;
	}
}
