//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : SequenceGenerator.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

import java.util.Map;

public class SequenceGenerator
{
	private static SequenceGenerator sequenceGenerator;
	private Map<String, Sequence> sequences;
	private void createSequenceGenerator()
	{
	}
	
	public static SequenceGenerator getInstance()
	{
	    return new SequenceGenerator();
	}
	
	public Sequence getSequence(String sequenceType)
	{
	    return null;
	}
	
	public void addSequence(Sequence sequence)
	{
	}
}
