package sg.edu.nus.iss.se23pt2.pos;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : ShoppingCart.java
//  @ Date : 3/8/2015
//  @ Author : Nikhil Metrani
//
//



/** */
public class ShoppingCart {

    /** */
    private ArrayList<Item> items;
    
    /** */
    private Customer customer;
    
    /** */
    private int points;
    
    /** */
    private Discount discount;
    
    /** */
    private String date;
    
	/** */
    public ShoppingCart() {
		this.items = new ArrayList<Item>();
		this.customer = new Customer();
		this.points = 0;
		this.discount = null;
		//TO-DO
		//this.date = 
    }
	
	public String getDate(){
		return this.date;
	}
	
	public ArrayList<Item> getItems() {
		return this.items;
	}
	
    /** */
    public Item addToCart(Product p, int quantity) {
		//TO-DO
		Item item = new Item();
		return item;
    }
    
    /** */
    public Item removeFromCart(Product p, int quantity) {
		//TO-DO
		Item item = new Item();
		return item;
    }
    
    /** */
    public Float getTotal() {
		Float total = Float.valueOf(0);
		return total;
    }
    
    public Integer getPoints() {
    	return this.points;
    }
    
    public Discount getDiscount() {
    	return this.discount;
    }
    
    /** */
    public void setMember(Member m) {
		this.customer = m;
    }
    
	/** */
    public Member getMember() {
		//TO-DO - type cast customer to member
		return (Member)this.customer;
    }
	
    /** */
    public void redeemPoints(int points) {
		//TO-DO
    }
    
    /** */
    public void applyDiscount(Discount d) {
		//TO-DO
    }
    
    /** */
    public Float getPayableAmount() {
		//TO-DO
		Float fl = Float.valueOf(0);
		return fl;
    }
    
    /** */
    public Transaction confirmTransaction() {
		Transaction t = new Transaction();
		//TO-DO
		return t;
    }
    
    /** */
    public Integer calculateNewPoints() {
		//TO-DO
		return 0;
    }
}
