//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : SouvenirStore
// @ File Name : SouvenirStore.java
// @ Date : 06/03/2015
// @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

import java.util.List;
import java.util.Map;


public class SouvenirStore {
    private Map<String, StoreKeeper> storeKeepers;
    private Map<String, Category>    categories;
    private Map<String, Vendor>      vendors;
    private List<Member>             members;
    private List<Discount>           discounts;
    private List<Transaction>        transactions;
    private List<BillInfo>           billInfos;
    private String                   loginUserName;

    public void addStoreKeeper (String userName, String password) {
    }

    public void addCategory (String categoryCode, String categoryName) {
    }

    public void addVendor (String vendorName, String description) {
    }

    public void addProduct (String productName, String description,
            Integer availableQty, Float price, Integer reorderThresholdQty,
            Integer orderQty) {
    }

    public void addMember (String memberName) {
    }

    public void addDiscount (String discountCode, String description,
            String startDate, String periodInDays, Integer discountPercentage,
            String applicableTo) {
    }

    public void addTransactionDetails (List<Transaction> transactions,
            BillInfo billInfo) {
    }

    public void updateDiscount (String discountCode, Integer discountPercentage) {
    }

    public void validateLogin (String userName, String password) {
    }

    public String getLoginUserName () {
        return null;
    }
}
