//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : StoreKeeper.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

public class StoreKeeper
{
	private String userName;
	private String password;
	public StoreKeeper(String userName, String password)
	{
	    this.userName = userName;
	    this.password = password;
	}
	
	public String getUserName()
	{
	    return userName;
	}
	
	public String getPassword()
	{
	    return password;
	}
	
	public Boolean isPasswordCorrect(String password)
	{
	    return this.password.equals(password);
	}
}
