//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : StoreKeeper.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

public class StoreKeeper
{
	private String userName;
	private String password;
	public void createStoreKeeper(String userName, String password)
	{
	}
	
	public String getUserName()
	{
	    return null;
	}
	
	public String getPassword()
	{
	    return null;
	}
	
	public Boolean isPasswordCorrect(String password)
	{
	    return false;
	}
}
