package sg.edu.nus.iss.se23pt2.pos;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : StoreKeeper.java
//  @ Date : 3/8/2015
//  @ Author : Nikhil Metrani
//
//



/** */
public class StoreKeeper {
    /** */
    private String name;
    
    /** */
    private String password;
    
	/** */
    public StoreKeeper() {
		this(null, null);
    }
	
    /** */
    public StoreKeeper(String name, String password) {
		this.name = name;
		this.password = password;
    }
    
    /** */
    public String getName() {
		return this.name;
    }
    
    /** */
    public void setName(String name) {
		this.name = name;
    }
    
    /** */
    public Boolean validatePassword(String password) {
		
		if (this.password.equals(password))
			return true; //validation successful
			
		return false; //validation failure
    }
    
    /** */
    public Boolean setPassword(String currentPassword, String newPassword, String confirmNewPassword) {
        this.password = newPassword;
		return false;
    }
    
    public Boolean isPasswordValid(String currentPassword, String newPassword, String confirmNewPassword) {
		if (this.password.equals(currentPassword)) {
			if (newPassword.equals(confirmNewPassword)) {
				return true;
			}
		}
		return false;
	}

    @Override
    public String toString(){
        return name + "," + password;
    }

    @Override
    public boolean equals(Object obj){
        if(obj instanceof StoreKeeper){
            return this.name.equals(((StoreKeeper)obj).name);
        }
        return false;
    }
}
