//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Transaction.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

import java.util.Date;

public class Transaction
{
	private String transactionId;
	private Product product;
	private String memberId;
	private Integer qtyPurchased;
	private Date txnDate;
	private String billInfoId;
	public void createTransaction(String transactionId, Product product, String memberId, Integer qtyPurchased)
	{
	}
	
	public void setTransactionId(String transactionId)
	{
	}
	
	public String getTransactionId()
	{
	    return null;
	}
	
	public Product getProduct()
	{
	    return null;
	}
	
	public String getMemberId()
	{
	    return null;
	}
	
	public Integer getQtyPurchased()
	{
	    return 0;
	}
	
	public Date getTxnDate()
	{
	    return new Date();
	}
	
	public void isOverThreshold(Boolean threshold)
	{
	}
}
