package sg.edu.nus.iss.se23pt2.pos;
import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Transaction.java
//  @ Date : 3/12/2015
//  @ Author : Rushabh Shah
//
//



/** */
public class Transaction {
    /** */
    private int id;
    
    /** */
    private ArrayList<Item> items;
    
    /** */
    private Customer customer;
    
    /** */
    private String date;
    
    /** */
    private Discount discount;
    
    /** */
    public Transaction() {
		this(0, null, null, null);
    }
	
    /** */
    public Transaction(int id, ArrayList<Item> items, Customer c, Discount d) {
    	this.id = id;
    	this.items = items;
    	this.customer = c;
    	this.discount = d;
    }
    
	/** */
    public void setId(int id) {
		this.id = id;
    }
	
    /** */
    public int getId() {
		return this.id;
    }
    
	/** */
    public void setItems(ArrayList<Item> items) {
		this.items = items;
    }
	
    /** */
    public ArrayList<Item> getItems() {
		return this.items;
    }

    /** */
    public Customer getCustomer() {
		return this.customer;
    }
    
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	/** */
    public void setDate(String date) {
		this.date = date;
    }
	
    /** */
    public String getDate() {
		return this.date;
    }
    
	/** */
    public void setDiscount(Discount d) {
		this.discount = d;
    }
	
    /** */
    public Discount getDiscount() {
		return this.discount;
    }   
    
	
	public String toString() {
		//for each item in items
		StringBuilder stb = new StringBuilder();
			for(Item item:items){
				stb = stb.append(this.id)
						 .append(" , ")
						 .append(item.getProductId())
						 .append(" , ")
						 .append(this.getCustomer().getId())
						 .append(" , ")
						 .append(item.getQuantity())
						 .append(System.getProperty("line.separator"));			
			}
		
		return stb.toString();
	}
}
