//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Vendor.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//


package sg.edu.nus.iss.se23pt2.pos;


public class Vendor
{
	private String vendorName;
	private String description;
	public void createVendor(String vendorName, String description)
	{
	}
	
	public String getVendorName()
	{
	    return null;
	}
	
	public String getDescription()
	{
	    return null;
	}
}
