package sg.edu.nus.iss.se23pt2.pos;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : Vendor.java
//  @ Date : 3/8/2015
//  @ Author : Nikhil Metrani
//
//



/** */
public class Vendor {
    /** */
    private String name;
    
    /** */
    private String description;
    
    /** */
    public PurchaseOrder po;
    
	/** */
    public Vendor() {
		this(null, null);
    }
	
    /** */
    public Vendor(String name, String description) {
		this.name = name;
		this.description = description;
    }
    
	/** */
    public void setName(String name) {
		this.name = name;
    }
	
    /** */
    public String getName() {
		return this.name;
    }
    
	/** */
    public void setDescription(String description) {
		this.description = description;
    }
	
    /** */
    public String getDescription() {
		return this.description;
    }
    
    /** */
    public void placeOrder(PurchaseOrder po) {
		this.po = po;
		return;
    }
    
    /** */
    public PurchaseOrder dispatchOrder() {
		return this.po;
    }
	
    @Override
	public String toString() {
		return this.name + "," + this.description;
	}
}
