//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : DataStoreFactory.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos.datastore;

import java.io.IOException;
import java.nio.file.AccessDeniedException;

public class DataStoreFactory
{
	private static DataStoreFactory dataStoreFactory = new DataStoreFactory();
	private DataStore storeKeeperDS;


	private void createDataStoreFactory()
	{
	}
	
	public static DataStoreFactory getInstance()
	{
	    return dataStoreFactory;
	}
	
	public DataStore getStoreKeeperDS() throws AccessDeniedException, IOException
	{
	    if(storeKeeperDS == null)
	        storeKeeperDS = new StoreKeeperDS();
	    return storeKeeperDS;
	}
	
	public DataStore getCategoryDS() throws AccessDeniedException, IOException
	{
	    return null;
	}
	
	public DataStore getVendorDS() throws AccessDeniedException, IOException
	{
	    return null;
	}
	
	public DataStore getProductDS() throws AccessDeniedException, IOException
	{
	    return null;
	}
	
	public DataStore getMemberDS() throws AccessDeniedException, IOException
	{
	    return null;
	}
	
	public DataStore getDiscountDS() throws AccessDeniedException, IOException
	{
	    return null;
	}
	
	public DataStore getTransactionDS() throws AccessDeniedException, IOException
	{
	    return null;
	}
	
	public DataStore getBillInfoDS() throws AccessDeniedException, IOException
	{
	    return null;
	}
}
