//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : DataStoreFactory.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos.datastore;

public class DataStoreFactory
{
	private static DataStoreFactory dataStoreFactory;
	private void createDataStoreFactory()
	{
	}
	
	public static DataStoreFactory getInstance()
	{
	    return new DataStoreFactory();
	}
	
	public DataStore getStoreKeeperDS()
	{
	    return null;
	}
	
	public DataStore getCategoryDS()
	{
	    return null;
	}
	
	public DataStore getVendorDS()
	{
	    return null;
	}
	
	public DataStore getProductDS()
	{
	    return null;
	}
	
	public DataStore getMemberDS()
	{
	    return null;
	}
	
	public DataStore getDiscountDS()
	{
	    return null;
	}
	
	public DataStore getTransactionDS()
	{
	    return null;
	}
	
	public DataStore getBillInfoDS()
	{
	    return null;
	}
}
