//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : DiscountDS.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos.datastore;

import java.io.IOException;
import java.nio.file.AccessDeniedException;
import java.util.ArrayList;

import sg.edu.nus.iss.se23pt2.pos.Discount;
import sg.edu.nus.iss.se23pt2.pos.MemberDiscount;
import sg.edu.nus.iss.se23pt2.pos.SouvenirStore;
import sg.edu.nus.iss.se23pt2.pos.exception.DataLoadFailedException;

public class DiscountDS extends DataStore
{
    private static final String fileName = "Discount.dat";

    public DiscountDS () throws AccessDeniedException, IOException {
        super(fileName);
    }

    @Override
    public ArrayList<Discount> load(SouvenirStore store)
            throws DataLoadFailedException {
        String line;
        String[] elements;
        Discount discount;
        ArrayList<Discount> discounts = new ArrayList<Discount>();
        try {
            while ((line = this.read()) != null) {
               if(line.length()>0){
	            	elements = line.split(",");
	                if(elements[5].equals("M"))
	                    discount = new MemberDiscount(elements[0], elements[1], elements[2], elements[3], Double.parseDouble(elements[4]), elements[5]);
	                else
	                    discount = new Discount(elements[0], elements[1], elements[2], elements[3], Double.parseDouble(elements[4]), elements[5]);
	                discounts.add(discount);
               }
            }
        } catch (IOException e) {
            throw new DataLoadFailedException(e.getMessage());
        } finally {
            this.close();
        }
        return discounts;
    }

    @Override
    protected <T> boolean matchData(T obj, String data) {
        String key = ((Discount) obj).getDiscountCode();
        if (data.indexOf( "," + key + ",") > 0)
            return true;
        return false;
    }
}
