//
//
// Generated by StarUML(tm) Java Add-In
//
// @ Project : SouvenirStore
// @ File Name : StoreKeeperDS.java
// @ Date : 06/03/2015
// @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos.datastore;

import java.io.IOException;
import java.nio.file.AccessDeniedException;
import java.util.ArrayList;

import sg.edu.nus.iss.se23pt2.pos.SouvenirStore;
import sg.edu.nus.iss.se23pt2.pos.StoreKeeper;
import sg.edu.nus.iss.se23pt2.pos.exception.DataLoadFailedException;

public class StoreKeeperDS extends DataStore {
    private static final String fileName = "StoreKeepers.dat";

    public StoreKeeperDS () throws AccessDeniedException, IOException {
        super(fileName);
    }

    @Override
    public <T> void update (T obj) {
        // There is no update to StoreKeeper for now
    }

    @Override
    public ArrayList<StoreKeeper> load (SouvenirStore store) throws DataLoadFailedException {
        String line;
        String[] elements;
        StoreKeeper storeKeeper;
        ArrayList<StoreKeeper> storeKeepers = new ArrayList<StoreKeeper>();
        try {
            while ((line = this.read()) != null) {
                elements = line.split(",");
                storeKeeper = new StoreKeeper(elements[0], elements[1]);
                storeKeepers.add(storeKeeper);
            }
        } catch (IOException e) {
            throw new DataLoadFailedException(e.getMessage());
        }
        return storeKeepers;
    }

    @Override
    public <T> void remove (T obj) {
        // There is no remove logic for StoreKeeper

    }
}
