//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : TransactionDS.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos.datastore;

import sg.edu.nus.iss.se23pt2.pos.SouvenirStore;

public class TransactionDS extends DataStore
{

    @Override
    public <T> void create (T obj) {
        // TODO Auto-generated method stub
        
    }

    @Override
    public <T> void update (T obj) {
        // TODO Auto-generated method stub
        
    }

    @Override
    public <T> void load (SouvenirStore store) {
        // TODO Auto-generated method stub
        
    }

    @Override
    public <T> void remove (T obj) {
        // TODO Auto-generated method stub
        
    }
}
