//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : VendorDS.java
//  @ Date : 06/03/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos.datastore;

import java.io.IOException;
import java.nio.file.AccessDeniedException;
import java.util.ArrayList;

import sg.edu.nus.iss.se23pt2.pos.SouvenirStore;
import sg.edu.nus.iss.se23pt2.pos.Vendor;
import sg.edu.nus.iss.se23pt2.pos.exception.DataLoadFailedException;

public class VendorDS extends DataStore
{

    public VendorDS (String type) throws AccessDeniedException, IOException {
        super("Vendors"+type+".dat");
    }

    @Override
    public ArrayList<Vendor> load (SouvenirStore store) throws DataLoadFailedException {
        String line;
        String[] elements;
        Vendor vendor;
        ArrayList<Vendor> vendors = new ArrayList<Vendor>();
        try {
            while ((line = this.read()) != null) {
                elements = line.split(",");
                vendor = new Vendor(elements[0], elements[1]);
                vendors.add(vendor);
            }
        } catch (IOException e) {
            throw new DataLoadFailedException(e.getMessage());
        } finally {
            this.close();
        }
        return vendors;
        
    }

    @Override
    protected <T> boolean matchData (T obj, String data) {
        String key = ((Vendor) obj).getName();
        if (data.indexOf(key + ",") == 0)
            return true;
        return false;
    }
}
