//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : FullTest.java
//  @ Date : 01/04/2015
//  @ Author : Jaya Vignesh
//
//

package sg.edu.nus.iss.se23pt2.pos;

import junit.framework.TestCase;
import junit.framework.TestSuite;
import sg.edu.nus.iss.se23pt2.pos.datastore.CategoryDSTest;
import sg.edu.nus.iss.se23pt2.pos.datastore.DiscountDSTest;
import sg.edu.nus.iss.se23pt2.pos.datastore.MemberDSTest;
import sg.edu.nus.iss.se23pt2.pos.datastore.ProductDSTest;
import sg.edu.nus.iss.se23pt2.pos.datastore.SequenceDSTest;
import sg.edu.nus.iss.se23pt2.pos.datastore.StoreKeeperDSTest;
import sg.edu.nus.iss.se23pt2.pos.datastore.TransactionDSTest;
import sg.edu.nus.iss.se23pt2.pos.datastore.VendorDSTest;

public class FullTest extends TestCase{
    public static TestSuite suite(){
        TestSuite suite = new TestSuite();
        suite.addTestSuite(SequenceDSTest.class);
        suite.addTestSuite(StoreKeeperDSTest.class);
        suite.addTestSuite(CategoryDSTest.class);
        suite.addTestSuite(VendorDSTest.class);
        suite.addTestSuite(DiscountDSTest.class);
        suite.addTestSuite(MemberDSTest.class);
        suite.addTestSuite(ProductDSTest.class);
        suite.addTestSuite(TransactionDSTest.class);
 
        suite.addTestSuite(CategoryTest.class);
        suite.addTestSuite(VendorTest.class);
        suite.addTestSuite(ProductTest.class);
        suite.addTestSuite(TransactionTest.class);
        suite.addTestSuite(ShoppingCartTest.class);
        return suite;
    }
}
