package sg.edu.nus.iss.se23pt2.posgui;

import sg.edu.nus.iss.se23pt2.pos.*;
import java.awt.GridLayout;
import java.awt.Panel;
import javax.swing.JDialog;
import javax.swing.JFrame;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SouvenirStore
//  @ File Name : DiscountDialog.java
//  @ Date : 23/03/2015
//  @ Author : Niu Yiming
//

public class DiscountDialog extends JFrame {


	private static final long serialVersionUID = 1L;
	private Inventory inventory = null;
	private JFrame parent = null;
	private DiscountPanel	discPanel;

	public DiscountDialog(Inventory inventory) {
		
		this.inventory = inventory;
		
		setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		setResizable(false);
		//setModal(true);
		//setModalityType(ModalityType.APPLICATION_MODAL);
		setTitle("Manage Discounts");
		setBounds(100, 100, 287, 310);
		getContentPane().setLayout(null);
		
		discPanel = new DiscountPanel(inventory, this);
		discPanel.refresh();
		Panel p = new Panel ();
        p.setLayout (new GridLayout(0, 1));
        p.add (discPanel);
		
        p.setBounds(10, 10, 267, 260);
		getContentPane().add(p);
	}
	
	private void UpdateJList(){
		/*
	    ListModel<String> model = new ListModel<String>();
	    ArrayList<Category> catList = this.inventory.getAllCategories();
	    for(Category c : catList){
	        model.addElement(c.toString());
	    }
	    .setModel(model);
	    clientJList.setSelectedIndex(0);*/
	}
}
