package sg.edu.nus.iss.se23pt2.posgui;

import sg.edu.nus.iss.se23pt2.pos.*;

import java.util.*;
import java.awt.*;
import java.awt.event.*;

import javax.swing.*;

//
//Generated by StarUML(tm) Java Add-In
//
//@ Project : SouvenirStore
//@ File Name : DiscountPanel.java
//@ Date : 23/03/2015
//@ Author : Niu Yiming
//

public class DiscountPanel extends JPanel {

	private static final long serialVersionUID = 1L;
	
	private Inventory        		inventory;
    private java.util.List<Discount> 	discounts;
    private java.awt.List          	discList;
    private JFrame					parent;
    
    public DiscountPanel (Inventory inventory, JFrame parent) {
        this.inventory = inventory;
        this.parent = parent;
        setLayout (new BorderLayout());
        discList = new java.awt.List (5);
        discList.setMultipleMode (false);
        add ("North", new JLabel ("Discounts"));
        add ("Center", discList);
        add ("East", createButtonPanel());
    }

    public void refresh () {
    	discounts = inventory.getDiscounts();
    	discList.removeAll();
        Discount disc = null;
        Iterator<Discount> i = discounts.iterator();
        while (i.hasNext()) {
        	disc = i.next();
        	discList.add (disc.getDiscCode());
        }
    }

    public Discount getSelectedDiscount () {
        int idx = discList.getSelectedIndex();
        return (idx == -1) ? null : discounts.get(idx);
    }

    private JPanel createButtonPanel () {

    	JPanel p = new JPanel (new GridLayout (0, 1, 5, 5));

        JButton b = new JButton ("Add");
        b.addActionListener (new ActionListener () {
            public void actionPerformed (ActionEvent e) {
                AddEditDiscountDialog d = new AddEditDiscountDialog(DiscountPanel.this.inventory, DiscountPanel.this.parent);
                d.setVisible (true);
                DiscountPanel.this.refresh();
            }
        });
        p.add (b);

        b = new JButton ("Remove");
        b.addActionListener (new ActionListener () {
            public void actionPerformed (ActionEvent e) {
            	if (null != DiscountPanel.this.getSelectedDiscount()) {
            		inventory.removeCategory(DiscountPanel.this.getSelectedDiscount().getDiscCode());
            		DiscountPanel.this.refresh();
            	}
            }
        });
        p.add (b);
        
        b = new JButton ("Edit");
        b.addActionListener (new ActionListener () {
            public void actionPerformed (ActionEvent e) {
            	if (null != DiscountPanel.this.getSelectedDiscount()) {
	            	AddEditDiscountDialog d = new AddEditDiscountDialog(DiscountPanel.this.getSelectedDiscount(), DiscountPanel.this.parent);
	                d.setVisible (true);
	                DiscountPanel.this.refresh();
            	}
            }
        });
        p.add (b);

        JPanel bp = new JPanel ();
        bp.setLayout (new BorderLayout());
        bp.add ("North", p);
        return bp;
    }

}